Henrique
CapDevMs/EaoQuadrado pull request #37
Opened 2024-11-05 11:16 UTC by H3nriqueSB

2024-11-08 14:21 UTC, annalorena22 requested changes
- Adicionar o "Bem- vindo, Fulano" acima do container de mudanças do perfil;
- Adicionar o "?" em "Alterar Senha";
- Alterar o arredondamento e a cor do botão "Salvar" como no figma.

2024-11-13 12:29 UTC, Braiani commented
Uma sugestão para próximas telas, utilizar nomes de classes/ids mais intuitivos.

Nomes como: "menuzin", menuzin2", "mi-cont-tittle" etc, não são tão intuitivos de qual parte da página eles se referem.

2025-01-27 11:56 UTC, Gabriel-Cs137 commented
Sobre qual tela se trata esse pull request?

2025-03-20 14:50 UTC, closed without merging

2025-03-20 14:50 UTC, RicardoDev08 commented
feio